[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-Tkernel/linker.ld",
    "-C", "link-arg=-znorelro",
    "-C", "link-arg=--no-pie",
    "-C", "relocation-model=static",
    "-C", "code-model=large",
]

[target.x86_64-unknown-uefi]
runner = "scripts/launch_qemu.sh"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
