[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-none]
linker = "rust-lld"

[target.x86_64-unknown-uefi]
runner = "scripts/launch_qemu.sh"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
